steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imageview:httpd', './httpd.d/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imageview:nginx', './nginx.d/']
images: ['gcr.io/$PROJECT_ID/imageview:httpd', 'gcr.io/$PROJECT_ID/imageview:nginx']
