apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      color: nginx
      color: server
  template:
    metadata:
      labels:
        type: webserver
        color: nginx
        type: system
        color: server
    spec:
      containers:
      - image: gcr.io/ciw0707-0517/imageview:nginx
        name: webserver-container
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: projectid
              key: project.id
        - name: SECRET_ID
          valueFrom:
            secretKeyRef:
              name: apikey
              key: id
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: apikey
              key: key
        ports:
        - containerPort: 80
          name: http-server
